my.service: Hello Login Service
db.value: "{connectionSting : 'http://---', userName : 'user', password : 'password'}"

app: 
 name: LoginService
 description: Creation of LoginService

db: 
 connection: dbconn
 host: host
 port: 1433

management.endpoints.web..exposure.include: "*"


spring: 
  cloud:
    config: 
     import: configserver
     uri: http://localhost:8888